language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2.3

before_install:
  - sudo apt install nuget
install:
  - dotnet restore 
  - nuget restore "Ab Math.sln"
script:
  - cd "Unit Tester/Apportionment/"
  - dotnet build 
  - dotnet test "Unit Tester.csproj" --verbosity n