language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2.3

before_install:
  - sudo apt install nuget
install:
  - dotnet restore 
  - nuget restore "Ab Math.sln"
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory "Unit Tester/Apportionment/"
script:
  - cd "Unit Tester/Apportionment/"
  - dotnet build 
  - mono ./NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./bin/Release/netcoreapp2.2/Unit Tester.dll