 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: dotnet restore
       - run: nuget restore "Ab Math.sln"
       - run: cd "Unit Tester/Apportionment/"
       - run: dotnet build 
       - run: dotnet test 
